[GLOBAL]
pants_version = "2.0.0rc1"
pantsd = true  # Enable the Pants daemon for better performance.
backend_packages.add = [
    'pants.backend.python',
    'pants.backend.python.lint.bandit',
    'pants.backend.python.lint.black',
    'pants.backend.python.lint.docformatter',
    'pants.backend.python.lint.flake8',
    'pants.backend.python.lint.isort',
    'pants.backend.python.typecheck.mypy',
]

# This ensures that the result of `./pants package` is always unique. It will become the default in
# Pants 2.1.
pants_distdir_legacy_paths = false

[source]
marker_filenames = ['setup.py']

[python-setup]
# The default interpreter compatibility for code in this repo. Individual targets can override
#  this with the `compatibility` field. See
#  https://www.pantsbuild.org/docs/python-interpreter-compatibility.
interpreter_constraints = [">=3.7"]
# Use a lockfile. See https://www.pantsbuild.org/docs/python-third-party-dependencies.
requirement_constraints = "tools/python/constraints.txt"
# We search for interpreters on both on the $PATH and in the `$(pyenv root)/versions` folder.
#  If you're using macOS, you may want to leave off the <PATH> entry to avoid using the
#  problematic system Pythons. See
#  https://www.pantsbuild.org/docs/python-interpreter-compatibility#changing-the-interpreter-search-path.
# interpreter_search_paths = ["<PATH>", "<PYENV>"]
interpreter_search_paths = ["<PYENV>"]

[docformatter]
args = ["--wrap-summaries=100", "--wrap-descriptions=100"]

[flake8]
config = "tools/python/.flake8"

[isort]
config = [".isort.cfg"]

[mypy]
config = "tools/python/.mypy.ini"
