#!/usr/bin/env bash

set -euo pipefail

PYTHON_BIN=python3
VIRTUALENV=tools/python/.venv
PIP="${VIRTUALENV}/bin/pip"
CONSTRAINTS_FILE=tools/python/constraints.txt

"${PYTHON_BIN}" -m venv "${VIRTUALENV}"
"${PIP}" install pip --upgrade
"${PIP}" install -r <(./pants dependencies --type=3rdparty ::)
echo "# Generated by tools/python/generate_constraints.sh on $(date)" > "${CONSTRAINTS_FILE}"
"${PIP}" freeze --all >> "${CONSTRAINTS_FILE}"

